export const PERFORM_FETCH_SHOPPING_ITEMS = 'PERFORM_FETCH_SHOPPING_ITEMS'; 
export const SUCCESS_FETCH_SHOPPING_ITEMS = 'SUCCESS_FETCH_SHOPPING_ITEMS';
export const ERROR_FETCH_SHOPPING_ITEMS = 'ERROR_FETCH_SHOPPING_ITEMS';
export const ADD_ITEM_QUANTITY = 'ADD_ITEM_QUANTITY';
export const DELETE_ITEM = 'DELETE_ITEM';
export const CALCULATE_ORDER = 'CALCULATE_ORDER';